STREAM_URL=
MUSIC_FOLDER=
SWEEPER_FOLDER=
ALSA_DEVICE=
MUSIC_WEIGHT=
SWEEPER_WEIGHT=
HEARTBEAT_URL=
MUSIC_WEIGHT=4
SWEEPER_WEIGHT=1
FILEBROWSER_ADDRESS="$FILEBROWSER_ADDRESS"
FILEBROWSER_PORT="$FILEBROWSER_PORT"

